name: k6 load test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs:
  k6-load-test:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - Checkout code
        uses: actions/checkout@v4
      
      - name: step 2 - k6 run performance test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: performance-test.js
          # options: |
          #   --vus 10
          #   --duration 30s
          #   --summary-export=./k6-summary.json
          #   --out json=./k6-output.json
      - run: ls & mkdir report & mv index.html report/
      - name: step 3 - Upload k6 summary
        uses: actions/upload-artifact@v4
        with:
          name: k6-summary-report
          path: report
      - name: step 4 - Publish k6 summary report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: report
